language: node_js
node_js:
    - "10"
script:
    - node build
cache:
    directories:
        - "node_modules"    
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
